// Generated by scripts/optimize-images.mjs. Do not edit by hand.
export const placeholders: Record<string, string> = {
  "portrait": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAAAQBACdASoQABgAPu1iqU2ppaOiMAgBMB2JYwC7ACG8m+vFT3qLqe5N4AD+rrxQZtXm5fW3PdK2st+haOD3+oKdi5T9nokX2QPVsALtNNgfn1RXmvZnIk/2UOQeBCURhp267jMJCdgnwi0hewGDWpXSWjhL4lOkQAAAAA==",
  "cover:asli-dhh": "data:image/webp;base64,UklGRlwAAABXRUJQVlA4IFAAAACwAwCdASoQABIAPu1iqU2ppaOiMAgBMB2JaQAAW+qtm3x01yvfcAD+8Ly4ANK1fwAopwTmDFTcH0HwJdDjUAo/+zxoKr7FWaLJHCFww9gAAA==",
  "cover:everything-feels": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAQAgCdASoQABAAA4BaJaQAAueEJZTA0RCgAP712IqC3S/NdWwK+/eNLeb43eU1BmIlKXJdi2iXvfjeTLwAAA==",
  "cover:indie-rock-2026": "data:image/webp;base64,UklGRlIAAABXRUJQVlA4IEYAAADQAQCdASoQAA0AA4BaJaQAAtq9CY0XAAD++RERbRxQM9Xo1onz3/AiAZM7JUGRPBthcD7mO/i5jasfEMbqciHp+73VQAAA",
  "cover:ki-scene-aa": "data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwAwCdASoQABEAPu1iqk2ppaQiMAgBMB2JZQAAW++YcY0HFu3HdAD+7pIHkiTrNJu8ed3IShxjF36ZNoQyqmFUUC6eELLxF3l8iaa4yGAmuwIFUKrGAAD0vXPW/rV+W9QSlex86mDZ+iwjp5vyRjdM63d9sJuZPMAAAA==",
  "thumb:3FinJRARyTI": "data:image/webp;base64,UklGRngAAABXRUJQVlA4IGwAAAAQAgCdASoQAAkAA4BaJQBOiP/wQLqzhIZsAP7mhfW93bwnRCNjMQCMFgpHGtVWCEMsFPT/Vtmczr7BmK2zi8UcUY2ukYEctmx8Pb91ZfFMd4S3fKWL92RRgf5wALQSa3DT9LeNnj2/W25oYAA=",
  "thumb:3nq8tMKMDwg": "data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoQAAkAA4BaJZAC7AEVYm35SD76AAD+8jVr7poRk4wsYivYtUY3e4+EePRQHwNIPAs2wbYap8FocXAy1Qj7gP8/45VYYjB3zdOha4BHRDkB+si5zQHAAAAA",
  "thumb:A_D18IaKgPw": "data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAADQAQCdASoQAAkAA4BaJYgCdADHmPZlsgD+volic8q0xBoM6R6r7yxcpP7Z752TvNdSOHF/NkuyUJpN4C10gvC7Lb7AAtFr/GzHeHlDu0aNUSAWet8MqR0sIeW85PabT/FrdnggAAA=",
  "thumb:VA5XiZy0GCw": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAQAgCdASoQAAkAA4BaJZACdADpLDxdICQAAP7useXmml2YEIxwGEFDkiZ5kLwdtNakAnkzDjgZKBg9jSVwmwGhlun+tNwGBiRzct+t2/Xwrvc8GR/FHSwA"
};
