// Turns the original images in assets-src/ into small WebP files in public/.
// Run with: npm run images
// It also writes tiny blurred previews to src/content/placeholders.ts.
import sharp from "sharp";
import { readdir, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const src = (...p) => path.join(root, "assets-src", ...p);
const out = (...p) => path.join(root, "public", ...p);

const placeholders = {};

async function blur(input, key) {
  const buf = await sharp(input).resize(16).webp({ quality: 40 }).toBuffer();
  placeholders[key] = `data:image/webp;base64,${buf.toString("base64")}`;
}

async function run() {
  await mkdir(out("images"), { recursive: true });
  await mkdir(out("covers"), { recursive: true });
  await mkdir(out("thumbs"), { recursive: true });

  // Founder portrait: two sizes plus a blur preview
  for (const w of [480, 900]) {
    await sharp(src("divyansh-portrait.png")).resize(w).webp({ quality: 78 }).toFile(out("images", `divyansh-portrait-${w}.webp`));
  }
  await blur(src("divyansh-portrait.png"), "portrait");

  // Artist photos (case studies): assets-src/artists/<name>.jpg → /images/<name>.webp
  for (const f of await readdir(src("artists"))) {
    const name = f.replace(/\.\w+$/, "");
    await sharp(src("artists", f)).resize(640).webp({ quality: 80 }).toFile(out("images", `${name}.webp`));
    await blur(src("artists", f), `artist:${name}`);
  }

  // Playlist covers (Spotify only gives ~300px, so keep native size, crop square)
  for (const f of await readdir(src("covers"))) {
    const name = f.replace(/\.\w+$/, "");
    await sharp(src("covers", f)).resize(300, 300, { fit: "cover" }).webp({ quality: 82 }).toFile(out("covers", `${name}.webp`));
    await blur(src("covers", f), `cover:${name}`);
  }

  // YouTube thumbnails
  for (const f of await readdir(src("thumbs"))) {
    const name = f.replace(/\.\w+$/, "");
    await sharp(src("thumbs", f)).resize(640).webp({ quality: 74 }).toFile(out("thumbs", `${name}.webp`));
    await blur(src("thumbs", f), `thumb:${name}`);
  }

  // App icons from the logo
  const logo = src("logo.png");
  await sharp(logo).resize(180).png().toFile(out("apple-touch-icon.png"));
  await sharp(logo).resize(192).png().toFile(out("icon-192.png"));
  await sharp(logo).resize(512).png().toFile(out("icon-512.png"));
  await sharp(logo).resize(32).png().toFile(out("favicon-32.png"));

  const body =
    "// Generated by scripts/optimize-images.mjs. Do not edit by hand.\n" +
    "export const placeholders: Record<string, string> = " +
    JSON.stringify(placeholders, null, 2) +
    ";\n";
  await writeFile(path.join(root, "src", "content", "placeholders.ts"), body);
  console.log("Images done:", Object.keys(placeholders).length, "placeholders");
}

run();
